name: Release
on:
  push:
    branches:
      - main


jobs:
  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch tags
        continue-on-error: true
        run: git fetch --tags

      - name: Get latest tag
        continue-on-error: true
        id: get_latest_tag
        run: |
          latest_tag=$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*' | sort -V | tail -n1)
          if [ -z "$latest_tag" ]; then
            latest_tag="v0.0.0"
          fi          
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Calculate next version
        id: calc_version
        run: |
          latest_tag=${{env.latest_tag}}
          if [ -z "$latest_tag" ]; then
            echo "No tags found, setting version to v0.1.0"
            new_version="v0.1.0"
          else
            major=$(echo "$version" | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+)/\1/')
            minor=$(echo "$version" | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+)/\2/')
            patch=$(echo "$version" | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+)/\3/')
            # Increment the PATCH version
            patch=$((patch + 1))
            echo $next
            new_version="v$major.$minor.$next"
          fi
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.calc_version.outputs.new_version }}
          release_name: "Release ${{ steps.calc_version.outputs.new_version }}"
          body: "Automated release for version ${{ steps.calc_version.outputs.new_version }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
