resource "local_file" "backend" {
  filename = "${var.output_dir}/backend.tf"
  content  = <<-EOF

            ##############################################
            ## THIS FILE IS AUTOGENERATED,  DO NOT EDIT ##
            ## -- EDIT BACKEND MODULE INPUTS INSTEAD -- ##
            ##############################################

    terraform {
      required_version = "${var.required_version}"
      required_providers ${indent(2, provider::terraform::encode_expr({ for k, v in var.required_providers : k => v }))}        
      
      backend "s3" {
        bucket = "${local.bucket_name}"
        key    = "${local.bucket_key}"
        region = "eu-west-1"

        dynamodb_table = "${local.dynamodb_table_arn}"
        encrypt        = true
        assume_role = {
          role_arn = "${local.role_arn}"
          session_name = "${var.prefix}-iac"
        }
      }
    }
  EOF
}
