
        ##############################################
        ## THIS FILE IS AUTOGENERATED,  DO NOT EDIT ##
        ## -- EDIT BACKEND MODULE INPUTS INSTEAD -- ##
        ##############################################

terraform {
  required_version = ">=1.9.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">=5.60.0"
    }
  }        
      
  backend "s3" {
    bucket = "backend-test-state-20240830151632434000000001"
    key    = "backend-test-dev.tfstate"
    region = "eu-west-1"

    dynamodb_table = "arn:aws:dynamodb:eu-west-1:013948180024:table/backend-test-dev-locktable"
    encrypt        = true
    assume_role = {
      role_arn = "arn:aws:iam::013948180024:role/backend-test-iac-role"
      session_name = "backend-test-iac"
    }
  }
}
