name: Distribute Changes

on: 
  push:
    branches:
      - main

jobs:
  update-subtrees:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: ['terraform-backend-manager']

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config pull.rebase false

      - name: Copy Module Files
        run: |
          cp -r ${{ matrix.module }} git-${{matrix.module}}
      - name: Git Init
        run: |
          cd git-${{matrix.module}} 
          git init

      - name: Add the target repo as a remote
        run: |
          cd git-${{matrix.module}} 
          git remote add ${{matrix.module}} https://$GITHUB_ACTOR:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Apollo-XIV/${{matrix.module}}.git
          git fetch ${{matrix.module}}

      - name: Push changes
        run: |
          cd git-${{matrix.module}} 
          git branch -m main
          # git checkout main
          git add .
          git commit -m 'chore: distribute module'
          git push --force -u ${{matrix.module}} main

      - name: Clean up remotes
        run: git remote remove ${{matrix.module}}

      # - name: Pull from target repo with --allow-unrelated-histories
      #   run: |
      #     git pull --allow-unrelated-histories ${{matrix.module}} main

      # - name: Add or update the subtree
        # run: |
          # git subtree add --prefix=${{matrix.module}} ${{matrix.module}} main --squash || git subtree pull --prefix=${{matrix.module}} ${{matrix.module}} main --squash

      # - name: Push changes back to target repo
      #   run: |
      #     git push ${{matrix.module}} HEAD:main

