name: Distribute Changes

on: 
  push:
    branches:
      - main

jobs:
  update-subtrees:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: ['terraform-backend-manager']

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch full history to avoid shallow clone issues
        run: git fetch --unshallow

      - name: Add the target repo as a remote
        run: |
          git remote add ${matrix.repo_name} https://$GITHUB_ACTOR:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Apollo-XIV/${matrix.repo_name}.git
          git fetch ${matrix.repo_name}

      - name: Pull from target repo with --allow-unrelated-histories
        run: |
          git pull --allow-unrelated-histories ${matrix.repo_name} main

      - name: Add or update the subtree
        run: |
          git subtree add --prefix=${matrix.folder_name} ${matrix.repo_name} main --squash || git subtree pull --prefix=${matrix.folder_name} ${matrix.repo_name} main --squash

      - name: Push changes back to target repo
        run: |
          git push ${matrix.repo_name} HEAD:main

      - name: Clean up remotes
        run: git remote remove ${matrix.repo_name}
