name: Distribute Changes

on: 
  push:
    branches:
      - main

jobs:
  update-subtrees:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - aws-backend-manager
          - aws-s3-backend
          - local-env-gen

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config pull.rebase false

      - name: Copy Module Files
        run: |
          cp -r ${{ matrix.module }} git-${{matrix.module}}
          mkdir -p git-${{matrix.module}}/.github/workflows
          cp release-template.yaml git-${{matrix.module}}/.github/workflows/release.yaml

      ## Idempotently Create Repo
          
      - name: Git Init
        run: |
          cd git-${{matrix.module}} 
          git init

      - name: Check if repository exists
        id: check_repo
        run: |
          REPO_NAME="terraform-${{matrix.module}}"
          RESPONSE=$(gh repo view Apollo-XIV/$REPO_NAME --json name --jq .name 2>/dev/null || echo "not found")
          echo "Repository status: $RESPONSE"
          if [ "$RESPONSE" = "not found" ]; then
            echo "repo_exists=false" >> $GITHUB_ENV
          else
            echo "repo_exists=true" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      - name: Create repository if it does not exist
        if: env.repo_exists == 'false'
        run: |
          gh repo create Apollo-XIV/terraform-${{matrix.module}} --public
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Add the target repo as a remote
        run: |
          cd git-${{matrix.module}} 
          git remote add ${{matrix.module}} https://$GITHUB_ACTOR:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Apollo-XIV/terraform-${{matrix.module}}.git
          git fetch ${{matrix.module}}

      - name: Push changes
        run: |
          cd git-${{matrix.module}} 
          git branch -m main
          # git checkout main
          git add .
          git commit -m 'chore: distribute module'
          git push --force -u ${{matrix.module}} main

      - name: Clean up remotes
        run: | 
          cd git-${{matrix.module}} 
          git remote remove ${{matrix.module}}

      # - name: Pull from target repo with --allow-unrelated-histories
      #   run: |
      #     git pull --allow-unrelated-histories ${{matrix.module}} main

      # - name: Add or update the subtree
        # run: |
          # git subtree add --prefix=${{matrix.module}} ${{matrix.module}} main --squash || git subtree pull --prefix=${{matrix.module}} ${{matrix.module}} main --squash

      # - name: Push changes back to target repo
      #   run: |
      #     git push ${{matrix.module}} HEAD:main

