name: Organise Jobs

on:
  push:
    branches:
      - main

jobs:
  changes:
    name: Detect module changes
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: steps.path-check.outputs.changed_dirs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: path-check
        uses: ./.github/actions/changes
    
  organise-jobs:
    if: ${{ !contains(needs.changes.outputs.changed_dirs, '[]') }} 
    needs:
      - changes
    name: Distribute on change
    strategy:
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.changed_dirs) }}
    uses: ./.github/workflows/distribute.yaml
    with:
      module: ${{matrix.module}}
    secrets: inherit
