
name: Organise Jobs

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      changed_dirs: ${{ steps.changed_dirs.outputs.changed_dirs }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Define Top-Level Changed Files
        id: changed_dirs
        run: |
          # Get the list of top-level directories/files that changed in the last commit
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | awk -F/ '{print $1}' | sort | uniq)
          # Filter directories/files by pattern: values interspersed by hyphens
          FILTERED_DIRS=$(echo "$CHANGED_FILES" | grep -E '^[a-zA-Z0-9]+(-[a-zA-Z0-9]+)+$')
          # Convert the filtered list to an array format
          TOP_LEVEL_FILES=$(printf '["%s"]' "$(echo $FILTERED_DIRS | tr ' ' '","')")
          echo "changed_dirs=$TOP_LEVEL_FILES" >> "$GITHUB_OUTPUT"
  organise-jobs:
    needs:
      - changes
    name: Distribute on change
    strategy:
      matrix:
        module: ${{ fromJSON(needs.define-matrix.outputs.changed_dirs) }}
    # uses: ./.github/actions/distribute
    uses: ./.github/workflows/distribute.yaml
    with:
      module: ${{matrix.module}}
      # PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
    secrets: inherit
