
name: Organise Jobs

on:
  push:
    branches:
      - main

jobs:
  organise-jobs:
    name: Distribute on change
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: 
          - aws-backend-manager
          - aws-s3-backend
          - local-env-gen
    steps:

      - name: Path filter
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            module:
              - '${{matrix.module}}/**'

      - name: Checkout
        if: steps.changes.outputs.module == 'true'
        uses: actions/checkout@v4

      - name: Run distribution workflow
        if: steps.changes.outputs.module == 'true'
        uses: ./.github/workflows/distribute.yaml
        with:
          module: ${{matrix.module}}
