
name: Organise Jobs

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      changed_dirs: ${{ steps.changed_dirs.outputs.changed_dirs }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: git fetch --prune --unshallow

      - name: Define and Filter Top-Level Changed Folders
        id: changed_dirs
        run: |
          # Get the list of top-level directories that changed in the last commit
          # Filter directories by pattern: values interspersed by hyphens
          # Convert the filtered list to a JSON array format
          CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | awk -F/ '{print $1}' | sort | uniq)
          echo $CHANGED_DIRS
          FILTERED_DIRS=$(echo "$CHANGED_DIRS" | grep -E '^[a-zA-Z0-9]+(-[a-zA-Z0-9]+)+$' || true)
          echo $FILTERED_DIRS
          if [ -n "$FILTERED_DIRS" ]; then
            TOP_LEVEL_DIRS=$(echo "$FILTERED_DIRS" | jq -R -s -c 'split("\n")[:-1]')
          else
            TOP_LEVEL_DIRS="[]"
          fi
          echo $TOP_LEVEL_DIRS
          echo "changed_dirs=$TOP_LEVEL_DIRS" >> "$GITHUB_OUTPUT"
  organise-jobs:
    if: ${{ needs.changes.outputs.chanded_dirs != '[]' }} 
    needs:
      - changes
    name: Distribute on change
    strategy:
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.changed_dirs) }}
    # uses: ./.github/actions/distribute
    uses: ./.github/workflows/distribute.yaml
    with:
      module: ${{matrix.module}}
      # PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
    secrets: inherit
