name: Organise Jobs

on:
  push:
    branches:
      - main

jobs:
  changes:
    name: Detect module changes
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{steps.changes.outputs.changed_dirs}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: changes
        uses: ./.github/actions/changes

  debug:
    name: Debug step
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - run: echo $DIRS
        env:
          DIRS: ${{needs.changes.outputs.changed_dirs}}

  organise-jobs:
    name: Distribute on change
    needs: changes
    if: ${{ !contains(needs.changes.outputs.changed_dirs,'') }} 
    strategy:
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.changed_dirs) }}
    uses: ./.github/workflows/distribute.yaml
    with:
      module: ${{matrix.module}}
    secrets: inherit
